package com.plagiarism_analysis.plagiarism_analysis.service;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

@Service
public class PlagiarismService {

    private static final java.lang.String INPUT_DIR = "D:/Downloads/Projects/plagiarism-analysis/src/main/resources/Inputs";  // Directory to store files

    // Save the uploaded file to the input directory
    public void saveFile(MultipartFile file) throws IOException {
        File dir = new File(INPUT_DIR);
        if (!dir.exists()) {
            dir.mkdirs();  // Create the directory if it doesn't exist
        }

        File outputFile = new File(dir, file.getOriginalFilename());
        try (FileOutputStream fos = new FileOutputStream(outputFile)) {
            fos.write(file.getBytes());
        }
    }

    // Run the plagiarism.py script and return the JSON response
    public List<String> runPlagiarismCheck() throws IOException, InterruptedException {
        ProcessBuilder processBuilder = new ProcessBuilder("python", "plagiarism.py");
        processBuilder.directory(new File("D:/Downloads/Projects/plagiarism-analysis/src/python/"));
        Process process = processBuilder.start();
        process.waitFor();

        // Read the output file generated by the script and convert it to list of list

        List<List<String>> jsonResponse = Files.readAllLines(Paths.get("D:/Downloads/Projects/plagiarism-analysis/src/python/output.json"));

    }
}
